apiVersion: v1
kind: Pod
metadata:
  name: incidentcmd-pod
spec:
  containers:
    - name: api
      image: localhost/incidentcmd-api:latest
      ports:
        - containerPort: 3000
          hostPort: 3001
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
